version: '3'
services:
  search:
    build: .
    environment:
      - DEBUG=1
    volumes:
      - ./:/app
    ports:
      - "${SEARCH_PORT}:${SEARCH_PORT}"
    command: python manage.py runserver 0.0.0.0:${SEARCH_PORT}
